---
# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Run OS-specific setup tasks
- name: Run OS-specific setup tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

# Ensure Pip is up-to-date
- name: Update Pip
  pip:
    executable: pip3.6
    name: pip
    state: latest

# Display Python packages to be installed
- name: Show selected Python packages
  debug:
    msg: "Packages: {{ python_packages | join(', ') }}"

# Install Python packages
- name: Install Python packages
  pip:
    executable: pip3.6
    name: "{{ python_packages }}"
    state: latest

- name: Add Python binary symlink
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: Register latest kubectl version
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    timeout: 10
    return_content: yes
  register: kubectl_version_response

- name: Install kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version_response.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/bin
    mode: 0755
