---
# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Run OS-specific setup tasks
- name: Run OS-specific setup tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

# Add a gemrc file
- name: Add gemrc
  copy:
    src: gemrc
    dest: /root/.gemrc
    owner: root
    group: root

# Install the sass gem
- name: Install SASS
  gem:
    name: sass
    state: present

# Ensure Pip is up-to-date
- name: Update Pip
  pip:
    executable: pip3.6
    name: pip
    state: latest

# Install PipEnv
- name: Install PipEnv
  pip:
    executable: pip3.6
    name: pipenv
    state: latest
